### ISSUE TITLE
Pipe into plotnine `ggplot` not working  - TypeError: __init__() missing 1 required positional argument: 'data'

### ISSUE THREAD

**Issue by rleyvasal** [pwwang/datar#41]
# Issue

`TypeError`  appears when piping data into plotnine `ggplot()` 

# Steps to replicate
`from datar.all import *`
`from plotnine import ggplot, aes,  theme_classic, geom_bar, aes`
`mtcars >> group_by(f.cyl) >> count() >> ggplot( aes(x ='cyl', y = 'n')) + geom_bar()`

# Expected 

Graph should show after piping data into `ggplot`

<img width="552" alt="ggplot_error" src="https://user-images.githubusercontent.com/61335136/126405107-3196df05-7de0-4da5-817c-250891198818.PNG">

**Comment by pwwang** [comment]
You need to register `ggplot` with `register_verb` from `pipda`:

```python
from pipda import register_verb
ggplot = register_verb(ggplot)

mtcars >> group_by(f.cyl) >> count() >> ggplot( aes(x ='cyl', y = 'n')) + geom_bar()
```

**Comment by pwwang** [comment]
Ahh, not sure why the `register_verb()` statement is gone in README...

**Comment by pwwang** [comment]
@rleyvasal Ignore my previous comments. `ggplot` doesn't need to be registered.

It works with plotnine 0.8.0

![image](https://user-images.githubusercontent.com/1188067/126406280-10623def-444a-4bce-b8ff-287fb9a47d30.png)


Could you check your plotnine version?

**Comment by pwwang** [comment]
Also check the versions from datar:

```python
import datar
datar.datar_versions()

# Diot({'pandas': '1.3.0', 'pipda': '0.4.2', 'varname': '0.7.1'})
```

**Comment by rleyvasal** [comment]
Thanks @pwwang, It is working now - I had pandas version 1.2.5 installed,

**Comment by pwwang** [comment]
Do you mean that it doesn't work with pandas 1.2.5?

**Comment by rleyvasal** [comment]
Not sure what the issue was. I tried again with pandas 1.2.5 and it works also. I suspect `mtcars` was not loaded for some reason.  

One more issue was that `geom_bar`  does not take a `y` variable so I had the error message in the picture below.

Note: The original error message was TypeError, the error when the `y` variable was included was a PlotnineError. 

You can close this issue. 

![image](https://user-images.githubusercontent.com/61335136/126532208-90cc3c6f-68ee-4261-8582-c68a902aee46.png)

**Comment by pwwang** [comment]
If `mtcars` was not loaded, `group_by` should throw an error. Just want to make sure what the issue was and try to document it.

I noticed that `aes` issue with `y` for `geom_bar` as well. That should be a `plotnine` issue.

I am closing this for now, but if it appears again, feel free to reopen.
