### ISSUE TITLE
register_verb  not working

### ISSUE THREAD

**Issue by antonio-yu** [pwwang/datar#152]
The  `register_verb ` doesn't work after I update datar to 0.9.1. It worked with olded version.
```
from datar.all import * 
from pipda import register_verb
from datar.datasets import mtcars
@register_verb
def copy_to_clipboard(df):
    return df.to_clipboard()

mtcars >> copy_to_clipboard()

TypeError: <lambda>() missing 1 required positional argument: 'fun'
```

**Comment by pwwang** [comment]
You need the type to be provided:

```python
from pandas import DataFrame

@register_verb(DataFrame)
def copy_to_clipboard(df):
  ...
```
